import { AlertTriangle, CheckCircle2, ChevronDown, LoaderCircle, Pill, ShieldCheck } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'

type Alert={id:string;risk_type:string;severity:'Contraindicated'|'Major'|'Moderate'|'Minor';summary:string;mechanism:string;clinical_effect:string;patient_context:string;recommended_action:string;evidence_source:string}
type Patient={name:string;initials:string;age:number;weight_kg:number;egfr:number;diagnoses:string[];allergies:{name:string;reaction:string}[];medications:{drug:string;dose_mg:number;frequency:string;started:string}[]}
const tint={Contraindicated:'border-red-500 bg-red-50 text-red-700',Major:'border-orange-500 bg-orange-50 text-orange-700',Moderate:'border-amber-400 bg-amber-50 text-amber-800',Minor:'border-sky-400 bg-sky-50 text-sky-700'}; const checks=['drug-drug interactions','drug-disease interactions','therapeutic duplication','dosage','allergies']
export default function Workspace(){
 const [patient,setPatient]=useState<Patient|null>(null),[drug,setDrug]=useState('Ibuprofen'),[dose,setDose]=useState('400'),[freq,setFreq]=useState('three times daily'),[running,setRunning]=useState(false),[done,setDone]=useState<string[]>([]),[alerts,setAlerts]=useState<Alert[]>([]),[open,setOpen]=useState(''),[audit,setAudit]=useState<any[]>([]),[override,setOverride]=useState(''),[note,setNote]=useState(''),[error,setError]=useState('')
 const load=async()=>{try{let [p,a]=await Promise.all([fetch('/api/patients/pt-001').then(x=>x.json()),fetch('/api/audit').then(x=>x.json())]);setPatient(p);setAudit(a)}catch{setError('Safety API unavailable. Start the FastAPI service to run live checks.')}};useEffect(()=>{load()},[])
 const counts=useMemo(()=>Object.fromEntries(Object.keys(tint).map(k=>[k,alerts.filter(a=>a.severity===k).length])),[alerts])
 async function run(){setError('');setAlerts([]);setDone([]);setRunning(true);for(const c of checks){await new Promise(r=>setTimeout(r,160));setDone(x=>[...x,c])}try{let r=await fetch('/api/check-safety',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({patient_id:'pt-001',prescription:{drug,dose_mg:+dose,frequency:freq}})});if(!r.ok)throw 0;setAlerts((await r.json()).alerts);load()}catch{setError('Live safety check failed. Verify that the API service is running.')}setRunning(false)}
 async function save(id:string){if(note.length<4)return;await fetch('/api/alerts/override',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({alert_id:id,justification:note})});setOverride('');setNote('');load()}
 if(!patient)return <main className="min-h-screen bg-slate-50 p-8 text-slate-800"><p className="mx-auto mt-40 max-w-md rounded-2xl bg-white p-5 shadow-sm">Loading clinician workspace…</p>{error&&<p className="mx-auto max-w-md pt-4 text-sm text-red-600">{error}</p>}</main>
 return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="sticky top-0 z-10 border-b border-slate-200 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6"><a href="#top" className="flex items-center gap-2 font-semibold"><b className="grid h-8 w-8 place-items-center rounded-xl bg-indigo-600 text-xs text-white">Rx</b> RxSentry <span className="hidden text-xs font-normal text-slate-400 sm:inline">Clinical safety workspace</span></a><span className="rounded-full bg-indigo-100 px-3 py-1 text-xs font-semibold text-indigo-700">Dr. Avery Patel</span></div></header><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6">
 <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-medium text-indigo-600">Patient safety review</p><h1 className="text-2xl font-semibold">{patient.name} <span className="font-mono text-sm font-normal text-slate-400">PT-001</span></h1></div><div className="flex gap-2 text-xs"><span className="rounded-full bg-slate-200 px-3 py-1">{patient.age}y · {patient.weight_kg}kg · eGFR {patient.egfr}</span><span className="rounded-full bg-red-50 px-3 py-1 font-semibold text-red-700">Penicillin allergy</span></div></div>
 <section className="mb-6 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><b>Risk summary</b><p className="text-xs text-slate-500">Current check results</p></div><b className="grid h-16 w-16 place-items-center rounded-full border-8 border-indigo-100 text-xl text-indigo-700">{alerts.length}</b></div><div className="mt-4 flex flex-wrap gap-2">{Object.entries(counts).map(([k,v])=><span key={k} className={`rounded-lg border px-2 py-1 text-xs font-bold ${tint[k as keyof typeof tint]}`}>{k} {v}</span>)}</div></div><div className="rounded-2xl bg-white p-5 shadow-sm"><b>Medication timeline</b><div className="mt-4 flex gap-5 overflow-x-auto">{patient.medications.map(m=><div className="min-w-36 border-l-2 border-indigo-300 pl-3" key={m.drug}><p className="font-medium">{m.drug}</p><p className="font-mono text-xs text-slate-500">{m.dose_mg} mg · {m.frequency}</p><p className="mt-2 text-xs text-slate-400">Since {m.started}</p></div>)}</div></div></section>
 <div className="grid gap-6 lg:grid-cols-[280px_1fr]"><aside className="space-y-5"><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="mb-4 flex items-center gap-2 font-semibold"><Pill className="h-4 text-indigo-600"/>Active medications</h2>{patient.medications.map(m=><p className="mb-3 flex justify-between text-sm" key={m.drug}><span>{m.drug}</span><span className="font-mono text-slate-500">{m.dose_mg} mg</span></p>)}</section><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="mb-3 font-semibold">Clinical context</h2><div className="flex flex-wrap gap-2">{patient.diagnoses.map(x=><span key={x} className="rounded-lg bg-slate-100 px-2 py-1 text-xs">{x}</span>)}{patient.allergies.map(x=><span key={x.name} className="rounded-lg bg-red-50 px-2 py-1 text-xs text-red-700">{x.name} · {x.reaction}</span>)}</div></section></aside>
 <div className="space-y-5"><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="mb-4 font-semibold">New prescription</h2><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs font-semibold">Drug<input list="drugs" value={drug} onChange={e=>setDrug(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-indigo-600"/><datalist id="drugs"><option>Ibuprofen</option><option>Amoxicillin</option><option>Lisinopril</option><option>Phenelzine</option></datalist></label><label className="text-xs font-semibold">Dose (mg)<input type="number" value={dose} onChange={e=>setDose(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 font-mono text-sm outline-none focus:ring-2 focus:ring-indigo-600"/></label><label className="text-xs font-semibold">Frequency<select value={freq} onChange={e=>setFreq(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-indigo-600"><option>daily</option><option>twice daily</option><option>three times daily</option></select></label></div><button disabled={running} onClick={run} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 py-3 text-sm font-semibold text-white transition hover:bg-indigo-700 disabled:opacity-60">{running?<LoaderCircle className="h-4 animate-spin"/>:<ShieldCheck className="h-4"/>}{running?'Running safety checks…':'Check safety'}</button>{running&&<div className="mt-3 text-sm">{checks.map(c=><p className={done.includes(c)?'text-emerald-700':'text-slate-400'} key={c}>{done.includes(c)?'✓':'⏳'} Checking {c}</p>)}</div>}</section>
 <section className="rounded-2xl bg-white p-5 shadow-sm"><div className="mb-4 flex justify-between"><div><h2 className="font-semibold">Live alerts</h2><p className="text-xs text-slate-500">Rules engine · clinician review required</p></div><AlertTriangle className="h-5 text-slate-400"/></div>{error&&<p className="mb-3 text-sm text-red-600">{error}</p>}{!running&&!alerts.length&&<div className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 className="mr-2 inline h-4"/>No conflicts found yet. A check evaluates {patient.medications.length} active medications, {patient.diagnoses.length} diagnoses, and {patient.allergies.length} allergy.</div>}<div className="space-y-3">{alerts.map(a=><article key={a.id} className={`overflow-hidden rounded-xl border-l-4 shadow-sm ${tint[a.severity]}`}><button onClick={()=>setOpen(open===a.id?'':a.id)} className="flex w-full items-center gap-3 bg-white p-4 text-left"><AlertTriangle className="h-5"/><div className="flex-1"><p className="text-xs font-bold uppercase">{a.severity} · {a.risk_type}</p><p className="mt-1 font-semibold text-slate-900">{a.summary}</p></div><ChevronDown className={`h-4 transition ${open===a.id?'rotate-180':''}`}/></button>{open===a.id&&<div className="border-t border-slate-100 bg-slate-50 p-4 text-sm text-slate-700"><p><b>Mechanism:</b> {a.mechanism}</p><p className="mt-2"><b>Clinical effect:</b> {a.clinical_effect}</p>{a.patient_context&&<p className="mt-2"><b>Patient context:</b> {a.patient_context}</p>}<p className="mt-3 rounded-lg bg-indigo-50 p-3 text-indigo-950"><b>Recommended action:</b> {a.recommended_action}</p><p className="mt-2 font-mono text-xs text-slate-400">{a.evidence_source}</p>{override===a.id?<div className="mt-3 flex gap-2"><input autoFocus value={note} onChange={e=>setNote(e.target.value)} placeholder="Clinical justification" className="min-w-0 flex-1 rounded-lg border px-2 text-sm"/><button onClick={()=>save(a.id)} className="rounded-lg bg-slate-900 px-3 text-xs font-semibold text-white">Confirm</button></div>:<button onClick={()=>setOverride(a.id)} className="mt-3 text-xs font-semibold text-indigo-700">Override with justification</button>}</div>}</article>)}</div></section>
 <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="mb-3 font-semibold">Audit history</h2>{audit.length?<div className="space-y-2 text-xs">{audit.slice(0,5).map(x=><p className="flex justify-between border-t pt-2" key={x.id}><span>{x.action}</span><span className="font-mono text-slate-400">{new Date(x.timestamp).toLocaleTimeString()}</span><span>{x.justification||x.prescription?.drug}</span></p>)}</div>:<p className="text-sm text-slate-500">Safety checks and documented overrides appear here.</p>}</section></div></div><footer className="py-8 text-center text-xs text-slate-400">Decision-support prototype — not a substitute for clinician or pharmacist judgment.</footer></div></main>
}
